_core:
  default_config_hash: Wkmn-jEru9OubwF4XTXJNzX89A62mX8PlyDco6TMYl4
langcode: es
smtp_host: localhost
smtp_hostbackup: ''
smtp_port: 25
smtp_protocol: ''
smtp_username: no-reply@obranovadigital.com
smtp_password: '!576Reanypyq8pZFx'
smtp_hide_password: true
smtp_authentication_type: basic_auth
smtp_fromname: ObraNovaDigital
smtp_always_replyto: false
smtp_keepalive: false
smtp_debug: 0
smtp_debug_log: false
phpmailer_smtp_test: ''
smtp_ssl_verify_peer: true
smtp_ssl_verify_peer_name: true
smtp_ssl_allow_self_signed: false
smtp_envelope_sender_option: default
smtp_envelope_sender: ''
smtp_ehlo_host: ''
smtp_timeout: 30
